name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main

jobs:

  test bloom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      # - name: Lint
      #   run: |
      #     cd bloom && make lint

      - name: Test
        # make test
        run: |
          make check

  build bloom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker
        run: |
          make docker

      - name: Docker image info
        run: |
          docker images


  build webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # todo: tests, lint
      - name: Build
        run: |
          cd webapp
          make install
          make build


  build chatbox.js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # todo: tests, lint
      - name: Build
        run: |
          cd chatbox.js
          make install
          make build

  build bloom.js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # todo: tests, lint
      - name: Build
        run: |
          cd bloom.js
          make install
          make build
